# Non-exhaustive list of animals
# todo: proper script to uniquify and sort

adjectives:
    - Absolute
    - Acid
    - Aerial
    - African
    - Agile
    - Alien
    - American
    - Antic
    - Arctic
    - Asian
    - Asiatic
    - Atomic
    - Australian
    - Bald
    - Beautiful
    - Big
    - Brutal
    - Caribbean
    - Caucasian
    - Chinese
    - Cool
    - Crazy
    - Creative
    - Curious
    - Cyber
    - Deaf
    - Deep
    - Devilish
    - Dreamy
    - Dutch
    - Eastern
    - Egyptian
    - Ethereal
    - Epic
    - Fast
    - Ferruginous
    - Fierce
    - French
    - Fuliginous
    - Funny
    - Generic
    - Genial
    - Gentle
    - German
    - Ghastly
    - Grumpy
    - Humble
    - Huge
    - Hybrid
    - Indian
    - Intrepid
    - Karmic
    - Laconic
    - Laughing
    - Lava
    - Mad
    - Magical
    - Mellow
    - Mongol
    - Mute
    - Mysterious
    - New
    - Open
    - Poor
    - Princess
    - Prussian
    - Psychedelic
    - Quantic
    - Raw
    - Relative
    - Relaxed
    - Romantic
    - Rich
    - Sad
    - Sensible
    - Shiny
    - Sick
    - Sleepy
    - Small
    - Superb
    - Spanish
    - Splendid
    - Swift
    - Tall
    - Tropical
    - Turkish
    - Unhinged
    - Veteran
    - Virulent
    - Vivid
    - Western
    - Wild
    - Winged
    - Wise
    - Witty

beings:
    - Aardwolf
    - Adjutant
    - Admiral
    - Adouri
    - Agouti
    - Albatross
    - Alligator
    - Alpaca
    - Anaconda
    - Andean
    - Android
    - Ant
    - Anteater
    - Antechinus
    - Antelope
    - Argalis
    - Armadillo
    - Ass
    - Avocet
    - Azaras
    - Baboon
    - Badger
    - Baleen
    - Banded
    - Bandicoot
    - Barasingha
    - Barbet
    - Bare
    - Barren
    - Barrows
    - Bat
    - Bateleur
    - Beaded
    - Beaked
    - Bear
    - Bearded
    - Beaver
    - Bee
    - Beisa
    - Bellied
    - Bengal
    - Bennetts
    - Bent
    - Bettong
    - Bighorn
    - Billed
    - Bird
    - Birds
    - Bison
    - Black
    - Blackbird
    - Blackbuck
    - Blackish
    - Blacksmith
    - Bleeding
    - Blesbok
    - Boa
    - Boar
    - Boat
    - Bobcat
    - Bohor
    - Bonnet
    - Bontebok
    - Booby
    - Bottle
    - Boubou
    - Box
    - Brazilian
    - Breasted
    - Brindled
    - Brocket
    - Brolga
    - Browed
    - Brown
    - Brush
    - Brushtail
    - Buckeye
    - Buffalo
    - Bulbul
    - Bunting
    - Burchells
    - Burmese
    - Burrowing
    - Bush
    - Bushbaby
    - Bushbuck
    - Bushpig
    - Bustard
    - Butcher
    - Butterfly
    - Buttermilk
    - Caiman
    - California
    - Camel
    - Campo
    - Canada
    - Canadian
    - Cape
    - Capped
    - Capuchin
    - Capybara
    - Caracal
    - Caracara
    - Cardinal
    - Caribou
    - Carmine
    - Carpet
    - Cat
    - Catfish
    - Cattle
    - Cereopsis
    - Chacma
    - Chameleon
    - Cheeked
    - Cheetah
    - Chestnut
    - Chickadee
    - Chilean
    - Chimpanzee
    - Chipmunk
    - Chital
    - Chuckwalla
    - Civet
    - Clarks
    - Clawed
    - Clawless
    - Cliffchat
    - Coatimundi
    - Cobra
    - Cockatoo
    - Cokes
    - Collared
    - Colobus
    - Columbian
    - Comb
    - Common
    - Constrictor
    - Cooks
    - Coot
    - Coqui
    - Cordon
    - Corella
    - Cormorant
    - Cottonmouth
    - Cottontail
    - Cougar
    - Cow
    - Coyote
    - Crab
    - Crake
    - Crane
    - Creeper
    - Crested
    - Crimson
    - Crocodile
    - Crow
    - Crown
    - Crowned
    - Cuis
    - Curlew
    - Currasow
    - Curve
    - Dabchick
    - Dama
    - Dark
    - Darter
    - Darwin
    - Dassie
    - Deer
    - Defassa
    - Denhams
    - Desert
    - Devil
    - Diamondback
    - Dik
    - Dingo
    - Dog
    - Dolphin
    - Double
    - Dove
    - Downy
    - Dragon
    - Dragonfly
    - Dromedary
    - Drongo
    - Duck
    - Duiker
    - Dunnart
    - Dusky
    - Dwarf
    - Eagle
    - Eared
    - Echidna
    - Egret
    - Egyptian
    - Eland
    - Elegant
    - Elephant
    - Eleven
    - Elk
    - Emerald
    - Emu
    - Eurasian
    - Euro
    - European
    - Eye
    - Eyed
    - Faced
    - Fairy
    - Falcon
    - False
    - Fat
    - Feathertail
    - Feral
    - Ferret
    - Finch
    - Fish
    - Flamingo
    - Fly
    - Flycatcher
    - Flying
    - Footed
    - Foreset
    - Fowl
    - Fox
    - Francolin
    - Frigate
    - Frilled
    - Fringe
    - Frog
    - Fruit
    - Galah
    - Gambels
    - Gaur
    - Gazelle
    - Gazer
    - Gargoyle
    - Gecko
    - Gelada
    - Gemsbok
    - Genet
    - Genoveva
    - Gerbil
    - Gerenuk
    - Giant
    - Gila
    - Giraffe
    - Glider
    - Gnu
    - Goanna
    - Goat
    - Godwit
    - Goldeneye
    - Goliath
    - Gonolek
    - Goose
    - Gopher
    - Gorilla
    - Grants
    - Grass
    - Gray
    - Great
    - Greater
    - Grebe
    - Green
    - Grenadier
    - Grey
    - Greylag
    - Griffon
    - Grison
    - Grizzly
    - Groundhog
    - Grouse
    - Guanaco
    - Guerza
    - Guinea
    - Gull
    - Hanuman
    - Hare
    - Hartebeest
    - Hawk
    - Headed
    - Heart
    - Hedgehog
    - Hen
    - Heron
    - Herring
    - Highland
    - Hippopotamus
    - Hoary
    - Hoffmans
    - Honey
    - Hoopoe
    - Hornbill
    - Horned
    - Hottentot
    - House
    - Howler
    - Hudsonian
    - Human
    - Hummingbird
    - Huron
    - Hyena
    - Hyrax
    - Ibex
    - Ibis
    - Iguana
    - Impala
    - Indigo
    - Insect
    - Jabiru
    - Jacana
    - Jackal
    - Jackrabbit
    - Jaeger
    - Jaguar
    - Jaguarundi
    - Japanese
    - Javan
    - Javanese
    - Jungle
    - Kaffir
    - Kafue
    - Kalahari
    - Kangaroo
    - Kelp
    - Killer
    - King
    - Kingfisher
    - Kinkajou
    - Kirks
    - Kiskadee
    - Kite
    - Klipspringer
    - Knob
    - Knobbed
    - Koala
    - Komodo
    - Kongoni
    - Kookaburra
    - Kori
    - Kudu
    - Land
    - Langur
    - Lappet
    - Lapwing
    - Large
    - Lark
    - Leadbeateris
    - Lechwe
    - Legaan
    - Legged
    - Lemming
    - Lemur
    - Leopard
    - Levaillants
    - Lightfoot
    - Lilac
    - Lily
    - Lined
    - Lion
    - Lipped
    - Little
    - Lizard
    - Llama
    - Lorikeet
    - Loris
    - Lory
    - Lourie
    - Lowland
    - Lynx
    - Macaque
    - Macaw
    - Madagascar
    - Magellanic
    - Magistrate
    - Magnificent
    - Magpie
    - Malabar
    - Malachite
    - Malagasy
    - Malay
    - Mallard
    - Malleefowl
    - Manatee
    - Mandras
    - Mantis
    - Mantled
    - Mara
    - Marabou
    - Margay
    - Marine
    - Marmot
    - Marshbird
    - Marten
    - Masked
    - Meadowlark
    - Meerkat
    - Melba
    - Mexican
    - Miners
    - Mississippi
    - Moccasin
    - Mocking
    - Mockingbird
    - Mongoose
    - Monitor
    - Monkey
    - Monster
    - Moorhen
    - Moose
    - Mouflon
    - Mountain
    - Mourning
    - Mouse
    - Mudskipper
    - Mule
    - Musk
    - Mynah
    - Native
    - Necked
    - Nelson
    - Neotropic
    - Netted
    - Night
    - Nighthawk
    - Nile
    - Nilgai
    - Nine
    - North
    - Northern
    - Nose
    - Nosed
    - Nubian
    - Numbat
    - Nutcracker
    - Nuthatch
    - Nyala
    - Ocelot
    - Of
    - Old
    - Olive
    - Onager
    - Openbill
    - Opossum
    - Orca
    - Oribi
    - Oriental
    - Ornate
    - Oryx
    - Osprey
    - Ostrich
    - Otter
    - Ovenbird
    - Owl
    - Ox
    - Oyster
    - Paca
    - Pacific
    - Paddy
    - Pademelon
    - Painted
    - Pale
    - Pallass
    - Palm
    - Pampa
    - Paradoxure
    - Parakeet
    - Parrot
    - Partridge
    - Patch
    - Peacock
    - Peccary
    - Pelican
    - Penguin
    - Peregrine
    - Phalarope
    - Phascogale
    - Pheasant
    - Pie
    - Pig
    - Pigeon
    - Pikachu
    - Pilot
    - Pine
    - Pink
    - Pintail
    - Plains
    - Platypus
    - Plover
    - Pocket
    - Polar
    - Polecat
    - Porcupine
    - Possum
    - Potoroo
    - Prairie
    - Praying
    - Pronghorn
    - Puffin
    - Puku
    - Puma
    - Puna
    - Pygmy
    - Python
    - Quail
    - Quoll
    - Rabbit
    - Raccoon
    - Racer
    - Radiated
    - Rainbow
    - Rat
    - Rattlesnake
    - Raven
    - Red
    - Reedbuck
    - Reindeer
    - Rhea
    - Rhesus
    - Rhinoceros
    - Ringtail
    - River
    - Roadrunner
    - Roan
    - Robin
    - Rock
    - Roe
    - Roller
    - Rose
    - Roseat
    - Roseate
    - Royal
    - Rufous
    - Rumped
    - Russian
    - Sable
    - Sacred
    - Saddle
    - Sage
    - Sally
    - Salmon
    - Sambar
    - Sandgrouse
    - Sandhill
    - Sandpiper
    - Sarus
    - Savanna
    - Savannah
    - Scaly
    - Scarlet
    - Scottish
    - Screamer
    - Scrub
    - Sea
    - Seal
    - Secretary
    - Serpent
    - Serval
    - Seven
    - Shark
    - Sheathbill
    - Sheep
    - Shelduck
    - Short
    - Shouldered
    - Shrew
    - Shrike
    - Sidewinder
    - Sifaka
    - Silver
    - Siskin
    - Skimmer
    - Skink
    - Skua
    - Skunk
    - Slender
    - Sloth
    - Smiths
    - Snake
    - Snow
    - Snowy
    - Sociable
    - Sockeye
    - South
    - Southern
    - Sparrow
    - Spectacled
    - Spider
    - Spoonbill
    - Springbok
    - Springbuck
    - Springhare
    - Spur
    - Spurfowl
    - Square
    - Squirrel
    - Stanley
    - Star
    - Starfish
    - Starling
    - Steenbok
    - Steenbuck
    - Steller
    - Stellers
    - Stick
    - Stilt
    - Stone
    - Stork
    - Sun
    - Sunbird
    - Sungazer
    - Suricate
    - Swainsons
    - Swallow
    - Swallowtail
    - Swamp
    - Swan
    - Tamandua
    - Tammar
    - Tanager
    - Tapir
    - Tarantula
    - Tasmanian
    - Tawny
    - Tayra
    - Teal
    - Tenrec
    - Tern
    - Thorns
    - Thrasher
    - Throated
    - Tiger
    - Timber
    - Tinamou
    - Toddy
    - Toed
    - Tokay
    - Toothed
    - Topi
    - Tortoise
    - Toucan
    - Tree
    - Trotter
    - Trumpeter
    - Tsessebe
    - Turaco
    - Turkey
    - Turtle
    - Tyrant
    - Uinta
    - Urial
    - Vampire
    - Verreauxs
    - Vervet
    - Vicuna
    - Vine
    - Viper
    - Vulture
    - Wagtail
    - Wallaby
    - Wallaroo
    - Wambenger
    - Wapiti
    - Warthog
    - Water
    - Waterbuck
    - Waxbill
    - Weaver
    - Weeper
    - Western
    - Whale
    - Whip
    - Whistling
    - White
    - Wildebeest
    - Wolf
    - Wombat
    - Woodchuck
    - Woodcock
    - Woodpecker
    - Woodrat
    - Woolly
    - Worm
    - Woylie
    - Yak
    - Zebra
    - Zorilla
    - Zorro

# todo : not really a todo, more like a marker
colors:
    - Alizarin
    - Alloy
    - Almond
    - Amaranth
    - Amazon
    - Amber
    - Amethyst
    - Ao
    - Apple
    - Apricot
    - Aqua
    - Aquamarine
    - Armpit
    - Army
    - Artichoke
    - Arylide
    - Ash
    - Asparagus
    - Auburn
    - Aureolin
    - Auro
    - Avocado
    - Aztec
    - Azure
    - Azureish
    - Baby
    - Baked
    - Ball
    - Banana
    - Bangladesh
    - Barbie
    - Barn
    - Battery
    - Battleship
    - Bazaar
    - Bdazzled
    - Bean
    - Beau
    - Beaver
    - Begonia
    - Beige
    - Bell
    - Berry
    - Big
    - Bill
    - Bisque
    - Bistre
    - Bitter
    - Bittersweet
    - Black
    - Blanched
    - Blast
    - Bleu
    - Blizzard
    - Blond
    - Blood
    - Blossom
    - Blue
    - Blueberry
    - Bluebonnet
    - Blush
    - Boat
    - Bole
    - Bolt
    - Bonbon
    - Bondi
    - Bone
    - Booger
    - Bottle
    - Boysenberry
    - Brandeis
    - Brass
    - Brick
    - Bright
    - Brilliant
    - Brink
    - British
    - Bronze
    - Brown
    - Brunswick
    - Bubble
    - Bubbles
    - Bud
    - Buff
    - Bulgarian
    - Burgundy
    - Burlywood
    - Burnished
    - Burnt
    - Buster
    - Byzantine
    - Byzantium
    - Cadet
    - Cadmium
    - Cafe
    - Cambridge
    - Camel
    - Cameo
    - Canary
    - Candy
    - Capri
    - Caput
    - Cardinal
    - Carmine
    - Carnation
    - Carnelian
    - Carolina
    - Carrot
    - Castleton
    - Catalina
    - Catawba
    - Cedar
    - Celadon
    - Celeste
    - Celestial
    - Cerise
    - Cerulean
    - Chalice
    - Chamoisee
    - Champagne
    - Charcoal
    - Charged
    - Charleston
    - Charm
    - Chartreuse
    - Cherry
    - Chest
    - Chestnut
    - Chiffon
    - Chlorophyll
    - Chocolate
    - Chrome
    - Cinereous
    - Cinnabar
    - Cinnamon
    - Citrine
    - Citron
    - Claret
    - Classic
    - Cobalt
    - Cocoa
    - Coconut
    - Coffee
    - Cool
    - Copper
    - Coquelicot
    - Coral
    - Cornflower
    - Cornsilk
    - Cosmic
    - Cotton
    - Coyote
    - Cream
    - Crimson
    - Cultured
    - Curry
    - Cyan
    - Cyber
    - Cyclamen
    - Cyclop
    - Daffodil
    - Dandelion
    - Dark
    - Deep
    - Desaturated
    - Desert
    - Diamond
    - Dingy
    - Dirt
    - Disco
    - Dodger
    - Dogwood
    - Dollar
    - Drab
    - Dream
    - Dregs
    - Duke
    - Dune
    - Dungeon
    - Dust
    - Dye
    - Earth
    - Ebony
    - Ecru
    - Eerie
    - Egg
    - Eggplant
    - Eggshell
    - Electric
    - Emerald
    - Erubescent
    - Eton
    - Eucalyptus
    - Eye
    - Fallow
    - Falu
    - Fandango
    - Fashion
    - Fawn
    - Feldgrau
    - Feldspar
    - Fern
    - Field
    - Fiery
    - Fire
    - Firebrick
    - Flame
    - Flamingo
    - Flattery
    - Flavescent
    - Flax
    - Flirt
    - Floral
    - Flower
    - Fluorescent
    - Folly
    - Forest
    - Free
    - Fresh
    - Frost
    - Frostbite
    - Fuchsia
    - Fulvous
    - Fusion
    - Fuzzy
    - Gainsboro
    - Gamboge
    - Gas
    - Ghost
    - Giants
    - Glace
    - Glacier
    - Glaucous
    - Glitter
    - Glory
    - Glossy
    - Gold
    - Golden
    - Goldenrod
    - Granite
    - Granny
    - Grape
    - Gras
    - Gray
    - Green
    - Grey
    - Grizzly
    - Grullo
    - Gum
    - Gunmetal
    - Guppie
    - Han
    - Hansa
    - Harlequin
    - Harvard
    - Harvest
    - Haze
    - Heart
    - Heat
    - Heidelberg
    - Heliotrope
    - Hollywood
    - Honeydew
    - Honolulu
    - Horse
    - Hot
    - Hunter
    - Ice
    - Iceberg
    - Icterine
    - Iguana
    - Illuminating
    - Imperial
    - Inchworm
    - Independence
    - India
    - Indian
    - Indigo
    - Infra
    - Iris
    - Irresistible
    - Isabelline
    - Islamic
    - Italian
    - Ivory
    - Jade
    - Jam
    - Japanese
    - Jasmine
    - Jasper
    - Jaune
    - Jazzberry
    - Jeans
    - Jelly
    - Jet
    - Jonquil
    - Jordy
    - June
    - Jungle
    - Kelly
    - Kenyan
    - Keppel
    - Key
    - Khaki
    - Kiwi
    - Kobe
    - Kobi
    - Kobicha
    - Kombu
    - Lace
    - Lagoon
    - Lait
    - Lake
    - Languid
    - Lapis
    - Laser
    - Latte
    - Laurel
    - Lava
    - Lavender
    - Lawn
    - Lazuli
    - Leaf
    - Leather
    - Lemon
    - Liberty
    - Licorice
    - Light
    - Lilac
    - Lime
    - Limerick
    - Linen
    - Lion
    - Liseran
    - Liver
    - Livid
    - Lizard
    - Lumber
    - Lust
    - Luster
    - Maastricht
    - Madder
    - Magenta
    - Magic
    - Magnolia
    - Mahogany
    - Maize
    - Majesty
    - Majorelle
    - Malachite
    - Manatee
    - Mandarin
    - Mango
    - Mania
    - Marigold
    - Maroon
    - Mass
    - Matter
    - Mauve
    - Mauvelous
    - Maximum
    - May
    - Maya
    - Meadow
    - Meat
    - Medium
    - Mellow
    - Melon
    - Meringue
    - Metal
    - Metallic
    - Mexican
    - Midnight
    - Mikado
    - Mimi
    - Mindaro
    - Ming
    - Minion
    - Mint
    - Mist
    - Misty
    - Mix
    - Moccasin
    - Mode
    - Moonstone
    - Mortuum
    - Moss
    - Mountain
    - Mountbatten
    - Mughal
    - Mulberry
    - Mummy
    - Mustard
    - Myrtle
    - Mystic
    - Napier
    - Naples
    - Navajo
    - Navy
    - Neon
    - New
    - Nickel
    - Noir
    - Nyanza
    - Ocean
    - Ochre
    - Octarine
    - Odor
    - Office
    - Ogre
    - Old
    - Olive
    - Olivine
    - Onyx
    - Opera
    - Orange
    - Orchid
    - Orioles
    - Otter
    - Outer
    - Outrageous
    - Oxford
    - Pacific
    - Pakistan
    - Palatinate
    - Pale
    - Palm
    - Pansy
    - Papaya
    - Paradise
    - Paris
    - Parrot
    - Pastel
    - Patriarch
    - Peach
    - Pear
    - Pearl
    - Pearly
    - Peel
    - Penny
    - Perfume
    - Peridot
    - Periwinkle
    - Persian
    - Persimmon
    - Peru
    - Phlox
    - Phthalo
    - Picton
    - Pictorial
    - Piggy
    - Pine
    - Pineapple
    - Pink
    - Pistachio
    - Pixie
    - Pizzazz
    - Platinum
    - Plum
    - Plump
    - Pomp
    - Poppy
    - Popstar
    - Portland
    - Potion
    - Powder
    - Power
    - Prune
    - Puce
    - Puff
    - Puke
    - Pumpkin
    - Purple
    - Purpureus
    - Quartz
    - Queen
    - Quick
    - Quinacridone
    - Rackley
    - Radical
    - Rain
    - Raisin
    - Rajah
    - Raspberry
    - Razzle
    - Razzmatazz
    - Razzmic
    - Rebecca
    - Red
    - Redwood
    - Reef
    - Regalia
    - Rhythm
    - Rifle
    - Roast
    - Robin
    - Rocket
    - Roman
    - Rose
    - Rosso
    - Rosy
    - Royal
    - Ruber
    - Rubine
    - Ruby
    - Ruddy
    - Rufous
    - Russet
    - Russian
    - Rust
    - Rusty
    - Saddle
    - Safety
    - Saffron
    - Sage
    - Salmon
    - Salsa
    - Sand
    - Sandstorm
    - Sandy
    - Sangria
    - Sanguine
    - Sapphire
    - Sasquatch
    - Satin
    - Saurus
    - Scarlet
    - Schauss
    - School
    - Screamin
    - Sea
    - Seal
    - Seashell
    - Seaweed
    - Selective
    - Sepia
    - Shadow
    - Shadows
    - Shampoo
    - Sheen
    - Sherbet
    - Shimmering
    - Shiny
    - Shocking
    - Shy
    - Sienna
    - Silk
    - Silver
    - Sinopia
    - Sizzling
    - Skobeloff
    - Sky
    - Slate
    - Slimy
    - Smalt
    - Smashed
    - Smitten
    - Smoke
    - Smokey
    - Smoky
    - Snow
    - Soap
    - Socks
    - Soda
    - Solid
    - Sonic
    - Space
    - Sparkle
    - Spartan
    - Spicy
    - Spiro
    - Spring
    - Star
    - Steel
    - Stizza
    - Storm
    - Stormcloud
    - Straw
    - Strawberry
    - Sugar
    - Sunburnt
    - Sunglow
    - Sunny
    - Sunray
    - Sunrise
    - Sunset
    - Sunshine
    - Super
    - Surf
    - Sweet
    - Tangelo
    - Tangerine
    - Tango
    - Tart
    - Taupe
    - Tea
    - Teal
    - Terra
    - Thistle
    - Thulian
    - Tickle
    - Tiffany
    - Tiger
    - Titanium
    - Tomato
    - Toolbox
    - Topaz
    - Tractor
    - Trolley
    - Tropical
    - True
    - Tufts
    - Tulip
    - Tumbleweed
    - Turquoise
    - Turtle
    - Tuscan
    - Tuscany
    - Twilight
    - Tyrian
    - Tyzantium
    - Ultra
    - Ultramarine
    - Umber
    - Unbleached
    - Unmellow
    - Upsdell
    - Urobilin
    - Vale
    - Vanilla
    - Venetian
    - Verdigris
    - Vermilion
    - Vermillion
    - Verte
    - Violet
    - Viridian
    - Volt
    - Warm
    - Watermelon
    - Waterspout
    - Wenge
    - Wheat
    - White
    - Wine
    - Winter
    - Wintergreen
    - Wisteria
    - Wizard
    - Wood
    - Wuzzy
    - Xanadu
    - Yale
    - Yankees
    - Yellow
    - Yonder
    - York
    - Zaffre
    - Zinnwaldite
    - Zomp
