# HOME
# We show the generated documentation and sandbox.
give2_peer_home:
    path:     /
    defaults: { _controller: Give2PeerBundle:Rest:index }

# Is out of the firewall.
# This should return info about the server so that clients may use it to choose
# configure themselves, like :
# - version number
# - news ?
give2_peer_hello:
    path:     /hello
    defaults: { _controller: Give2PeerBundle:Rest:ping, _format: json }
    methods:  [GET]

# Like 'hello', but to check if credentials work too.
# Checks :
# - credentials given in HTTPAuth
# - nothing else for now
give2_peer_authenticate:
    path:     /check
    defaults: { _controller: Give2PeerBundle:Rest:ping, _format: json }
    methods:  [GET]

## USERS #######################################################################

give2_peer_change_password:
    path:     /change/password
    defaults: { _controller: Give2PeerBundle:Rest/User:changePassword, _format: json }
    methods:  [POST]

give2_peer_change_username:
    path:     /change/username
    defaults: { _controller: Give2PeerBundle:Rest/User:changeUsername, _format: json }
    methods:  [POST]

give2_peer_register:
    path:     /register
    defaults: { _controller: Give2PeerBundle:Rest/User:register, _format: json }
    methods:  [POST]

## PROFILES ####################################################################

# Public profile of provided `username`, or my own private profile otherwise.
give2_peer_profile:
    path:     /profile
    defaults: { _controller: Give2PeerBundle:Rest:profile, _format: json }
    methods:  [GET]

## ITEMS #######################################################################

give2_peer_item_add:
    path:     /item
    defaults: { _controller: Give2PeerBundle:Rest:itemAdd, _format: json }
    methods:  [POST]

give2_peer_item_delete:
    path:     /item/{id}
    defaults: { _controller: Give2PeerBundle:Rest:itemDelete, _format: json }
    methods:  [DELETE]
    requirements:
        id:   \d+

give2_peer_picture_upload:
    path:     /item/{id}/picture
    defaults: { _controller: Give2PeerBundle:Rest:itemPictureUpload, _format: json }
    methods:  [POST]
    requirements:
        id:   \d+

give2_peer_items_around:
    path:     /items/around/{latitude}/{longitude}
    defaults: { _controller: Give2PeerBundle:Rest:itemsAround, _format: json }
    methods:  [GET]
    requirements:
        latitude:   "[+-]?\d+(?:[.,]\d*)?|[+-]?[.,]\d+"
        longitude:  "[+-]?\d+(?:[.,]\d*)?|[+-]?[.,]\d+"

## GENERAL DATA COLLECTION #####################################################

give2_peer_tags:
    path:     /tags
    defaults: { _controller: Give2PeerBundle:Rest\Data:tags, _format: json }
    methods:  [GET]

give2_peer_stats:
    path:     /stats
    defaults: { _controller: Give2PeerBundle:Rest\Data:stats, _format: json }
    methods:  [GET]
