give2_peer_home:
    path:     /
    defaults: { _controller: Give2PeerBundle:Rest:index }

give2_peer_ping:
    path:     /ping
    defaults: { _controller: Give2PeerBundle:Rest:ping, _format: json }
    methods:  [GET]

## USERS #######################################################################

give2_peer_register:
    path:     /register
    defaults: { _controller: Give2PeerBundle:Rest:register, _format: json }
    methods:  [POST]

give2_peer_profile:
    path:     /profile
    defaults: { _controller: Give2PeerBundle:Rest:profile, _format: json }
    methods:  [GET]

give2_peer_public_profile:
    path:     /profile/{username}
    defaults: { _controller: Give2PeerBundle:Rest:publicProfile, _format: json }
    methods:  [GET]

## ITEMS #######################################################################

# Deprecated alias for POST /item
give2_peer_give:
    path:     /give
    defaults: { _controller: give2peerbundle:rest:give, _format: json }
    methods:  [post]

# Deprecated alias for POST /item
give2_peer_spot:
    path:     /spot
    defaults: { _controller: Give2PeerBundle:Rest:spot, _format: json }
    methods:  [POST]

give2_peer_item_add:
    path:     /item
    defaults: { _controller: Give2PeerBundle:Rest:itemAdd, _format: json }
    methods:  [POST]

give2_peer_picture_upload:
    path:     /item/{id}/picture
    defaults: { _controller: Give2PeerBundle:Rest:itemPictureUpload, _format: json }
    methods:  [POST]
    requirements:
        id:   \d+

# fixme: /items and then ?q= parameters
give2_peer_find_around:
    path:     /items/find/{latitude}/{longitude}/{skip}/{radius}
    defaults:
        _controller: Give2PeerBundle:Rest:findAroundCoordinates
        _format: json
        skip:   0 # don't skip anything
        radius: 0 # will be handled as infinity (no filter)
    methods:  [GET]
    requirements:
        latitude:   -?\d+(?:\.\d*)?
        longitude:  -?\d+(?:\.\d*)?
        skip:         \d+
        radius:       \d+(?:\.\d*)?

## GENERAL DATA COLLECTION #####################################################

give2_peer_tags:
    path:     /tags
    defaults: { _controller: Give2PeerBundle:Rest:tags, _format: json }
    methods:  [GET]