give2_peer_home:
    path:     /
    defaults: { _controller: Give2PeerBundle:Rest:index }

give2_peer_ping:
    path:     /ping
    defaults: { _controller: Give2PeerBundle:Rest:ping, _format: json }
    methods:  [GET]

give2_peer_register:
    path:     /register
    defaults: { _controller: Give2PeerBundle:Rest:register, _format: json }
    methods:  [POST]

give2_peer_give:
    path:     /give
    defaults: { _controller: Give2PeerBundle:Rest:give, _format: json }
    methods:  [POST]

give2_peer_spot:
    path:     /spot
    defaults: { _controller: Give2PeerBundle:Rest:spot, _format: json }
    methods:  [POST]

give2_peer_picture_upload:
    path:     /picture/{itemId}
    defaults: { _controller: Give2PeerBundle:Rest:pictureUpload, _format: json }
    methods:  [POST]
    requirements:
        itemId: \d+

give2_peer_tags:
    path:     /tags
    defaults: { _controller: Give2PeerBundle:Rest:tags, _format: json }
    methods:  [GET]

give2_peer_find_around:
    path:     /find/{latitude}/{longitude}/{skip}/{radius}
    defaults:
        _controller: Give2PeerBundle:Rest:findAroundCoordinates
        _format: json
        skip: 0
        radius: 0 # will be handled as infinity (no filter)
    methods:  [GET]
    requirements:
        latitude:   -?\d+(?:\.\d*)?
        longitude:  -?\d+(?:\.\d*)?
        skip:         \d+
        radius:       \d+(?:\.\d*)?