give2_peer_home:
    path:     /
    defaults: { _controller: Give2PeerBundle:Rest:index }

give2_peer_ping:
    path:     /ping
    defaults: { _controller: Give2PeerBundle:Rest:ping, _format: json }
    methods:  [GET]

## USERS #######################################################################

give2_peer_register:
    path:     /register
    defaults: { _controller: Give2PeerBundle:Rest:register, _format: json }
    methods:  [POST]

give2_peer_profile:
    path:     /profile
    defaults: { _controller: Give2PeerBundle:Rest:profile, _format: json }
    methods:  [GET]

give2_peer_public_profile:
    path:     /profile/{username}
    defaults: { _controller: Give2PeerBundle:Rest:publicProfile, _format: json }
    methods:  [GET]

## ITEMS #######################################################################

give2_peer_item_add:
    path:     /item
    defaults: { _controller: Give2PeerBundle:Rest:itemAdd, _format: json }
    methods:  [POST]

give2_peer_picture_upload:
    path:     /item/{id}/picture
    defaults: { _controller: Give2PeerBundle:Rest:itemPictureUpload, _format: json }
    methods:  [POST]
    requirements:
        id:   \d+

give2_peer_items_around:
    path:     /items/around/{latitude}/{longitude}
    defaults: { _controller: Give2PeerBundle:Rest:itemsAround, _format: json }
    methods:  [GET]
    requirements:
      latitude:   "[+-]?\d+(?:[.,]\d*)?|[+-]?[.,]\d+"
      longitude:  "[+-]?\d+(?:[.,]\d*)?|[+-]?[.,]\d+"

## GENERAL DATA COLLECTION #####################################################

give2_peer_tags:
    path:     /tags
    defaults: { _controller: Give2PeerBundle:RestData:tags, _format: json }
    methods:  [GET]

give2_peer_stats:
    path:     /stats
    defaults: { _controller: Give2PeerBundle:RestData:stats, _format: json }
    methods:  [GET]
