give2_peer_home:
    path:     /
    defaults: { _controller: Give2PeerBundle:Rest:index }

give2_peer_give:
    path:     /give
    defaults: { _controller: Give2PeerBundle:Rest:give }
    methods:  [POST]

give2_peer_spot:
    path:     /spot
    defaults: { _controller: Give2PeerBundle:Rest:spot }
    methods:  [POST]

give2_peer_list_by_coordinates:
    path:     /list/{latitude}/{longitude}/{skip}
    defaults:
        _controller: Give2PeerBundle:Rest:listAroundCoordinates
        skip: 0
    methods:  [GET]
    requirements:
        latitude:   -?\d+(?:\.\d*)?
        longitude:  -?\d+(?:\.\d*)?
        skip:         \d+