give2_peer_home:
    path:     /
    defaults: { _controller: Give2PeerBundle:Rest:index }

give2_peer_give:
    path:     /give
    defaults: { _controller: Give2PeerBundle:Rest:give }
    methods:  [POST]

give2_peer_spot:
    path:     /spot
    defaults: { _controller: Give2PeerBundle:Rest:spot }
    methods:  [POST]