# This is loaded by our DependencyInjection\Give2PeerExtension
# List of tags : http://symfony.com/doc/current/reference/dic_tags.html

services:

    # We roll our own user manager, with username generation and so on.
    g2p.user_manager:
        class: Give2Peer\Give2PeerBundle\Entity\UserManager
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @fos_user.entity_manager
            - Give2Peer\Give2PeerBundle\Entity\User

    # Every Item we serialize and send back in the responses must be painted
    # by the ItemPainter, who will create and inject the URLs of the images.
    # The ItemPainter can be used alone, but it's also hooked into Doctrine.
    g2p.item_painter:
        class: Give2Peer\Give2PeerBundle\Service\ItemPainter
        arguments:
            - @request_stack
            - %give2peer.items.pictures.directory%
            - %give2peer.items.pictures.url_path%
            - %give2peer.items.pictures.thumbnails.sizes%
        tags:
            - { name: doctrine.event_listener, event: postLoad  }
            - { name: doctrine.event_listener, event: preRemove }

    # Register a listener that reads the request header 'Accept-Language' and
    # sets the locale accordingly.
    # /!\ This totally bypasses the _locale attribute of routing.
    #     We're probably not doing it right ; why do we even need this ?
    g2p.locale_listener:
        class: Give2Peer\Give2PeerBundle\EventSubscriber\Locale
        arguments: ['%kernel.default_locale%', '%locales%']
        tags:
            - { name: kernel.event_subscriber }

    # Register the SoftDeleteableListener to doctrine events,
    # and make sure to inject an annotaions reader into it.
    # The softdeletable filter itself is enabled in config.yml.
    # Why do I even need this ? These are defaults, no ?
    # Why does the SoftDeleteable bundle not handle this !?
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
