# List of tags : http://symfony.com/doc/current/reference/dic_tags.html

services:
    g2p.authentication:
        class: Give2Peer\Give2PeerBundle\EventSubscriber\Authentication
        arguments:
            - @security.token_storage
            - @fos_user.user_manager
        tags:
            - { name: kernel.event_subscriber }