
# The released and publicized API, version 1.
give2peer_api_v1:
    resource: "@Give2PeerBundle/Resources/config/routing.yml"
    prefix:   /v1


# Deprecated
# Actually this does not even work ? It's overwriten by NelmioApiDocBundle_1
# Why ? Why !? WHY !? @lutangar
#NelmioApiDocBundle_2:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc

NelmioApiDocBundle_1:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /