#!/usr/bin/env php
<?php

/*
 * Our tailored feature suite runner, using behat.
 * Symlink it to `bin/behat` for convenience.
 */

use Doctrine\Common\Annotations\AnnotationRegistry;

define('BEHAT_BIN_PATH', __FILE__);

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    } else {
        return false;
    }
}

if ((!$loader = includeIfExists(__DIR__.'/../vendor/autoload.php'))) {
    fwrite(STDERR,
        'You must set up the project dependencies, run:'.PHP_EOL.
        'curl -s http://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL
    );
    exit(1);
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This whole file (and the setup_behat script) exist just for these miserable hacks.

// Hot fix to skip phpunit XML config and Other Trouble ©
// May break at any given time, of course. Holler me if it does !
$_SERVER['KERNEL_DIR'] = 'app';

// Doctrine and the documentation generator NEED annotations support
AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// Start Behat
$factory = new \Behat\Behat\ApplicationFactory();
$factory->createApplication()->run();
