#!/usr/bin/env php
<?php

/*
 * Our tailored feature suite runner, using behat.
 * Symlink it to `bin/behat` for convenience.
 */

use Doctrine\Common\Annotations\AnnotationRegistry;

define('BEHAT_BIN_PATH', __FILE__);

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    } else {
        return false;
    }
}

if ((!$loader = includeIfExists(__DIR__.'/../vendor/autoload.php'))) {
    fwrite(STDERR,
        'You must set up the project dependencies, run:'.PHP_EOL.
        'curl -s http://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL
    );
    exit(1);
}


// Yeah... About that... Sorry ! If you're lucky I'll fix this someday.
// It's TOO DANGEROUS to delete the files (for now), in case the suite is
// (un)willingly run on the production server, and havoc ensues.
// Ideally, the test env should use another upload dir that we can safely
// overwrite and delete, and this would be solved.
// And if you think writing these comments took longer than to fix, think again.
// Or, hey, even better : prove it ! ;)
// ... later ...
// Wait. Didn't I solve this earlier in the big configuration refacto ? Yay ! \o/
// echo "/!\\ WILL GENERATE A BUNCH OF DUMMY IMAGE FILES IN `web/pictures/`.\n";

// Hot fix to skip phpunit XML config and Other Trouble ©
// May break at any given time, of course. Holler me if it does !
$_SERVER['KERNEL_DIR'] = 'app';

// Doctrine and the documentation generator NEED annotations support
AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

// Start Behat
$factory = new \Behat\Behat\ApplicationFactory();
$factory->createApplication()->run();
